name: Deploy to Google Cloud Run

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/figma-mcp

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy figma-mcp \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/figma-mcp \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated \
            --port 3000